### ISSUE TITLE
Problem running script

### ISSUE THREAD

**Issue by bhuebner3** [TangJiakai/RecBole-FairRec#3]
When running
 python run_recbole.py
I receive

Traceback (most recent call last):
  File "c:\Users\e12139066\Documents\Thesis\RecBole-FairRec\run_recbole.py", line 26, in <module>
    run_recbole(model=args.model, dataset=args.dataset, config_file_list=config_file_list)
  File "c:\Users\e12139066\Documents\Thesis\RecBole-FairRec\recbole\quick_start\quick_start.py", line 56, in run_recbole
    best_valid_score, best_valid_result = trainer.fit(
  File "c:\Users\e12139066\Documents\Thesis\RecBole-FairRec\recbole\trainer\trainer.py", line 377, in fit      
    valid_score, valid_result = self._valid_epoch(valid_data, show_progress=show_progress)
  File "c:\Users\e12139066\Documents\Thesis\RecBole-FairRec\recbole\trainer\trainer.py", line 1043, in _valid_epoch
    valid_result = self.pfcn_evaluate(valid_data, load_best_model=False, show_progress=show_progress)
  File "C:\Users\e12139066\.conda\envs\Algos\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "c:\Users\e12139066\Documents\Thesis\RecBole-FairRec\recbole\trainer\trainer.py", line 1023, in pfcn_evaluate
    self.eval_collector.eval_batch_collect(scores, interaction, positive_u, positive_i)
  File "c:\Users\e12139066\Documents\Thesis\RecBole-FairRec\recbole\evaluator\collector.py", line 179, in eval_batch_collect
    self.data_struct.update_tensor('rec.positive_score', scores_tensor[positive_u, positive_i])
IndexError: tensors used as indices must be long, byte or bool tensors

I have not changed the default model, data, or any settings.

**Comment by TangJiakai** [comment]
Hi, thanks for your attention! Your problem has been questioned in RecBole project. I think you could refer [https://github.com/RUCAIBox/RecBole/issues/1041](url). Hope this could solve your problem!

**Comment by bhuebner3** [comment]
Hi, thanks for the help. I followed the advice from issue 1041.

If I insert the following code into recbole/trainer/trainer.py, the row_idx.dtype is int32
`print('row_idx.dtype', row_idx.dtype)
print('col_idx.dtype', col_idx.dtype)
exit()`

I then replaced lines 455 and 946 with the following code

`scores[row_idx.long(), col_idx.long()] = origin_scores`

The resulting error is
RuntimeError: shape mismatch: value tensor of shape [505, 1] cannot be broadcast to indexing result of shape [505]

I also tried changing the dtype of row_idx using
`row_idx = row_idx.type(torch.int64)`
and receive the same original error
IndexError: tensors used as indices must be long, byte or bool tensors

**Comment by TangJiakai** [comment]
Actually, I can run normally locally. Then, I find your error is `shape mismatch`, so could you try squeeze the row_idx.long() and col_idx.long()? (btw, I cannot make sure your repo is the newest source code I published.)

**Comment by bhuebner3** [comment]
Thanks, I didn't see you pushed updated code last week. But now I get a new error:

Traceback (most recent call last):
  File "run_recbole.py", line 26, in <module>
    run_recbole(model=args.model, dataset=args.dataset, config_file_list=config_file_list)
  File "C:\Users\e12139066\Documents\Thesis\RecBole-FairRec\recbole\quick_start\quick_start.py", line 57, in run_recbole
    train_data, valid_data, saved=saved, show_progress=config['show_progress']
  File "C:\Users\e12139066\Documents\Thesis\RecBole-FairRec\recbole\trainer\trainer.py", line 583, in fit
    self.pretrain(train_data, valid_data, verbose, saved, show_progress)
  File "C:\Users\e12139066\Documents\Thesis\RecBole-FairRec\recbole\trainer\trainer.py", line 625, in pretrain  
    train_loss = self._train_epoch_with_mask(train_data, epoch_idx, show_progress=show_progress, sst_list=None) 
  File "C:\Users\e12139066\Documents\Thesis\RecBole-FairRec\recbole\trainer\trainer.py", line 721, in _train_epoch_with_mask
    losses = loss_func(interaction, sst_list)
  File "C:\Users\e12139066\Documents\Thesis\RecBole-FairRec\recbole\model\fair_recommender\fairgo_gcn.py", line 192, in calculate_loss
    user_all_embeddings, item_all_embeddings = self.forward(sst_list)
  File "C:\Users\e12139066\Documents\Thesis\RecBole-FairRec\recbole\model\fair_recommender\fairgo_gcn.py", line 176, in forward
    all_embedding = self.gcn(all_embedding, self.edge_indices, self.edge_weights)
  File "C:\Users\e12139066\Anaconda3\envs\Run_Algo_37\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() takes 3 positional arguments but 4 were given

**Comment by bhuebner3** [comment]
Here is my environment:
Python 3.7.12
recbole 1.1.1
numpy 1.21.6
torch 1.12.1
tqdm>=4.64.1

Operating system: Windows Server 2022 Standard
cudatoolkit version none

**Comment by TangJiakai** [comment]
Thanks for your issue! I have update the code, welcome to use again!

**Comment by bhuebner3** [comment]
Thanks! But I am still getting the error
IndexError: tensors used as indices must be long, byte or bool tensors

**Comment by TangJiakai** [comment]
😂Index error again, hah! Maybe you could use the same method mentioned before to solve it? This bug is relatively easy to fix.

**Comment by bhuebner3** [comment]
I have tried this suggestion below by replacing lines 455 and 946 in recobole/trainer/trainer.py with the suggested line below, but then I get the error:
RuntimeError: shape mismatch: value tensor of shape [505, 1] cannot be broadcast to indexing result of shape [505]

https://github.com/RUCAIBox/RecBole/issues/1041#issuecomment-966929343

Hello, thank you for your interest in the RecBole project! The problem you reported was also mentioned in https://github.com/RUCAIBox/RecBole/issues/1012 . It is not a leave-one-out problem, but the tensor is inconsistent in different environments . You can try to add the following code between lines 407 and 408 of to check whether your and of meet the format requirements of indices.row_idxdtypetensors used as indices must be long, byte or bool tensorsrecbole/trainer/trainer.pyrow_idxcol_idxdtype

print('row_idx.dtype', row_idx.dtype)
print('col_idx.dtype', col_idx.dtype)
exit()
If dtypenot int64, you can fix this little problem by:

**scores[row_idx.long(), col_idx.long()] = origin_scores**

**Comment by TangJiakai** [comment]
Yeah, the same as https://github.com/TangJiakai/RecBole-FairRec/issues/3#issuecomment-1378790573, have you tried squeezing the idx? i.e., if you squeeze the idx tensor, then you will not receive the shape mismatch error.

**Comment by bhuebner3** [comment]
So lines 455 and 946 should read as below?
`scores[torch.squeeze(row_idx.long()), torch.squeeze(col_idx.long())] = origin_scores`

That results in the same error:
RuntimeError: shape mismatch: value tensor of shape [505, 1] cannot be broadcast to indexing result of shape [505]

**Comment by TangJiakai** [comment]
Maybe could you try squeezing origin_scores? I am so sorry that I cannot know what differences make you fail to execute the source code.

**Comment by bhuebner3** [comment]
It's not problem, I appreciate the help :)

Squeezing origin_scores results in the IndexError.
IndexError: tensors used as indices must be long, byte or bool tensors

**Comment by TangJiakai** [comment]
You mean it appears bug when you use code as follows?
`scores[torch.squeeze(row_idx.long()), torch.squeeze(col_idx.long())] = torch.squeeze(origin_scores)`

**Comment by bhuebner3** [comment]
Yes I tried running both below, and both result in the Index Error

`scores[torch.squeeze(row_idx.long()), torch.squeeze(col_idx.long())] = torch.squeeze(origin_scores)`

`scores[row_idx.long(), col_idx.long()] = torch.squeeze(origin_scores)`

**Comment by TangJiakai** [comment]
How about scores[torch.squeeze(row_idx).long(), torch.squeeze(col_idx).long()] = torch.squeeze(origin_scores)
I think it is supposed to make sure index type belongs to long tensors, thus it would report Index error.
Or maybe the error is not caused by this line?

**Comment by bhuebner3** [comment]
The full traceback is the same as the original https://github.com/TangJiakai/RecBole-FairRec/issues/3#issue-1528858684
so it seems like the error comes when the trainer script calls the evaluator function.

Also it runs through the first epoch of training and fails when it gets to the evaluate step.

**Comment by TangJiakai** [comment]
> 

If your bug is the same with https://github.com/TangJiakai/RecBole-FairRec/issues/3#issue-1528858684, that is, `scores_tensor[positive_u, positive_i]`, could you evaluate the data type of positive_u or positive_i (if not belong to long type, just try converting them.)

**Comment by bhuebner3** [comment]
I did your suggestion and it seems to be working now, thanks!
